import os
import subprocess

from github import Github

from core.state.manifest import TaskManifest, PipelineStatus


def run(manifest: TaskManifest) -> TaskManifest:
    token = os.getenv("GITHUB_TOKEN")
    org = os.getenv("GITHUB_ORG")
    local_path = manifest.repo_local_path
    branch = f"autopilot/{manifest.jira_id.lower()}"

    # Create and push branch
    subprocess.run(["git", "-C", local_path, "checkout", "-B", branch], check=True)
    subprocess.run(["git", "-C", local_path, "add", "."], check=True)
    subprocess.run(
        ["git", "-C", local_path, "commit", "-m", f"feat: autopilot generated code for {manifest.jira_id}"],
        check=True,
    )
    subprocess.run(["git", "-C", local_path, "push", "origin", branch, "--force"], check=True)
    print(f"✅ Pushed branch {branch}")

    # Open PR
    g = Github(token)
    owner = g.get_organization(org) if org else g.get_user()
    repo = owner.get_repo(manifest.repo_name)

    spec_summary = (manifest.spec_doc or "")[:500]
    pr = repo.create_pull(
        title=f"[Autopilot] {manifest.jira_id} — generated implementation",
        body=f"## Autopilot Generated PR\n\n**Jira ID:** {manifest.jira_id}\n\n### Spec Summary\n{spec_summary}\n\n---\n*Generated by Autopilot*",
        head=branch,
        base=repo.default_branch,
    )

    print(f"✅ PR opened: {pr.html_url}")
    manifest.status = PipelineStatus.DONE
    return manifest
