# agents/commit/agent.py
import os, shutil
from github import Github
from core.state.manifest import TaskManifest, PipelineStatus

def run(manifest: TaskManifest) -> TaskManifest:
    g = Github(os.getenv("GITHUB_TOKEN"))
    repo = g.get_repo(os.getenv("GITHUB_REPO"))
    branch_name = f"aifsd/{manifest.jira_id.lower()}"

    # Get base SHA
    base = repo.get_branch("main")
    repo.create_git_ref(
        ref=f"refs/heads/{branch_name}",
        sha=base.commit.sha
    )

    # Push each file
    all_files = {
        **(manifest.generated_code or {}),
        **(manifest.generated_tests or {})
    }
    for filepath, content in all_files.items():
        try:
            existing = repo.get_contents(filepath, ref=branch_name)
            repo.update_file(filepath, f"AIFSD: {manifest.jira_id}",
                             content, existing.sha, branch=branch_name)
        except:
            repo.create_file(filepath, f"AIFSD: {manifest.jira_id}",
                             content, branch=branch_name)

    # Open PR
    pr = repo.create_pull(
        title=f"[{manifest.jira_id}] {manifest.story_text[:60]}",
        body=f"**Jira:** {manifest.jira_id}\n\n**Spec:**\n{manifest.spec_doc}\n\n"
             f"**Coverage:** {manifest.review_result.coverage:.1f}%\n\n"
             f"**Auto-generated by AIFSD**",
        head=branch_name,
        base="main"
    )

    manifest.status = PipelineStatus.DONE
    return manifest